services:
  upload.annoation_reader:
    class: Ad\UploadBundle\Annotation\UploadAnnotationReader
    arguments: ["@annotations.reader"]

  upload.handler:
    class: Ad\UploadBundle\Handler\UploadHandler

  upload.subscriber:
    class: Ad\UploadBundle\Listener\UploadSubsciber
    arguments: ["@upload.annoation_reader","@upload.handler"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }