<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'secit.imap' shared service.

include_once $this->targetDirs[3].'\\vendor\\secit-pl\\imap-bundle\\Service\\Imap.php';

return $this->services['secit.imap'] = new \SecIT\ImapBundle\Service\Imap($this->parameters['secit.imap.connections']);
