<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sg_datatables.response' shared service.

include_once $this->targetDirs[3].'\\vendor\\sg\\datatablesbundle\\Response\\DatatableResponse.php';

return $this->services['sg_datatables.response'] = new \Sg\DatatablesBundle\Response\DatatableResponse(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'});
