<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'upload.handler' shared service.

include_once $this->targetDirs[3].'\\src\\Ad\\UploadBundle\\Handler\\UploadHandler.php';

return $this->services['upload.handler'] = new \Ad\UploadBundle\Handler\UploadHandler();
