<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'upload.subscriber' shared service.

include_once $this->targetDirs[3].'\\vendor\\doctrine\\event-manager\\lib\\Doctrine\\Common\\EventSubscriber.php';
include_once $this->targetDirs[3].'\\src\\Ad\\UploadBundle\\Listener\\UploadSubsciber.php';
include_once $this->targetDirs[3].'\\src\\Ad\\UploadBundle\\Handler\\UploadHandler.php';

return $this->services['upload.subscriber'] = new \Ad\UploadBundle\Listener\UploadSubsciber(${($_ = isset($this->services['upload.annoation_reader']) ? $this->services['upload.annoation_reader'] : $this->load('getUpload_AnnoationReaderService.php')) && false ?: '_'}, ${($_ = isset($this->services['upload.handler']) ? $this->services['upload.handler'] : ($this->services['upload.handler'] = new \Ad\UploadBundle\Handler\UploadHandler())) && false ?: '_'});
