<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'upload.annoation_reader' shared service.

include_once $this->targetDirs[3].'\\src\\Ad\\UploadBundle\\Annotation\\UploadAnnotationReader.php';

return $this->services['upload.annoation_reader'] = new \Ad\UploadBundle\Annotation\UploadAnnotationReader(${($_ = isset($this->services['annotations.reader']) ? $this->services['annotations.reader'] : $this->getAnnotations_ReaderService()) && false ?: '_'});
