<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFio1lkm\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFio1lkm/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFio1lkm.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFio1lkm\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFio1lkm\appDevDebugProjectContainer([
    'container.build_hash' => 'Fio1lkm',
    'container.build_id' => '9e596960',
    'container.build_time' => 1604673941,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFio1lkm');
